mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  ipv6: true
  default-nameserver: [223.5.5.5, 8.8.8.8, 223.6.6.6, 119.29.29.29]
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
  fallback: [https://doh.dns.sb/dns-query, https://dns.cloudflare.com/dns-query, https://dns.twnic.tw/dns-query, tls://8.8.4.4:853]
  fallback-filter: {geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32]}
